read.table("household_power_consumption.txt",sep=";",header=TRUE,colClasses= c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric') ,skip=0,na.strings="?")
png("plot3.png")
plot(data$Sub_metering_1, type = "l", ylab = "Energy sub metering")
lines(data$Sub_metering_2, type = "l", col = "red")
lines(data$Sub_metering_3, type = "l", col = "blue")
dev.off()
